### ISSUE TITLE
How to run mochat in a development environment without using nginx?

### ISSUE THREAD

**Issue by JooKS-me** [mochat-cloud/mochat-java#16]
## 我用的环境

* Java 版本：jdk1.8
* MoChat 版本：latest
* MySQL 版本：5.7

## 问题及现象

Hi, 我clone了mochat-java的代码后，成功运行了后端代码。当我使用`yarn run dev`运行dashboard模块之后，成功进入了登陆页面。

但是当输入账户密码，且点击登陆之后，产生了404错误，如下图。
![image](https://user-images.githubusercontent.com/62384022/119762059-97e0ab00-bedf-11eb-8e7e-c52ec2b0cecd.png)
原因是前端直接向8000端口发起请求，而不是我配置的9501端口。

application.yml中部分配置如下：
```yml
server:
  port: 9501

chat-tools:
  #API地址
  apiUrl: http://127.0.0.1
  #web后台地址
  webUrl: http://127.0.0.1
```

我想知道是否可以通过修改一些东西，使得可以直接向9501端口发起请求，不需要经过Nginx转发？
